[build]
  publish = 'dist'
  command = 'NOTION_TOKEN=${NOTION_TOKEN_CI:-$NOTION_TOKEN} NOTION_DB_ID=${NOTION_DB_ID_CI:-$NOTION_DB_ID} yarn build'
  ignore = '/bin/true'
[functions]
  directory = 'netlify/functions'
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
[[redirects]]
  from = "/party/new"
  to = "/party"
  status = 301
[[redirects]]
  from = "/api/party/*"
  to = "/.netlify/functions/party"
  status = 200
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/static/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/giscus-theme.css"
  [headers.values]
    Access-Control-Allow-Origin = "https://giscus.app"
