[build]
  base = 'site'
  publish = 'public'
  command = 'yarn build'
[[headers]]
  for = "*.js" # cache immutable js files for up to 1 year
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/static/*.mp3" # cache immutable mp3 files for up to 1 year
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"