[build]
  base = 'site'
  publish = 'public'
  command = 'yarn build'
[build.environment]
  NETLIFY_USE_YARN = 'true'
  NODE_VERSION = '14.7.3'
[[headers]]
  for = "*.js" # cache immutable js files for up to 1 year
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/static/*.mp3" # cache immutable mp3 files for up to 1 year
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"